<?php

declare(strict_types=1);

namespace Retina\Report\Format;

use Retina\Issue\Issue;
use Retina\Scanner\ScanResult;

class MarkdownFormatter implements FormatterInterface
{
    public function format(ScanResult $result): string
    {
        $output = [];

        $output[] = '# Retina Scan Report';
        $output[] = '';
        $output[] = '## Plugin Information';
        $output[] = '';
        $output[] = '| Property | Value |';
        $output[] = '|----------|-------|';
        $output[] = sprintf('| **Name** | %s |', $result->getPluginName());
        $output[] = sprintf('| **Version** | %s |', $result->getPluginVersion());
        $output[] = sprintf('| **Path** | `%s` |', $result->getPluginPath());
        $output[] = sprintf('| **Scan Date** | %s |', $result->getScanDate()->format('Y-m-d H:i:s'));
        $output[] = sprintf('| **Scan Duration** | %.2fs |', $result->getScanDuration());
        $output[] = '';

        $output[] = '## Summary';
        $output[] = '';
        $output[] = sprintf('- **Files Scanned:** %d', $result->getScannedFileCount());
        $output[] = sprintf('- **Files with Issues:** %d', $result->getAffectedFileCount());
        $output[] = sprintf('- **Total Issues:** %d', $result->getTotalIssueCount());
        $output[] = '';

        $summary = $result->getSummary();
        $nonZeroSummary = array_filter($summary, fn($count) => $count > 0);

        if (!empty($nonZeroSummary)) {
            $output[] = '### Issues by Category';
            $output[] = '';
            $output[] = '| Category | Count |';
            $output[] = '|----------|-------|';
            foreach ($nonZeroSummary as $category => $count) {
                $output[] = sprintf('| %s | %d |', $category, $count);
            }
            $output[] = '';
        }

        $issuesByFile = $result->getIssuesByFile();

        if (!empty($issuesByFile)) {
            $output[] = '## Issues by File';
            $output[] = '';

            foreach ($issuesByFile as $file => $issues) {
                $relativeFile = $this->getRelativePath($file, $result->getPluginPath());
                $output[] = sprintf('### `%s`', $relativeFile);
                $output[] = '';

                foreach ($issues as $issue) {
                    $output[] = $this->formatIssue($issue, $result->getPluginPath());
                }

                $output[] = '';
            }
        }

        if ($result->getTotalIssueCount() === 0) {
            $output[] = '## ✅ No Issues Found';
            $output[] = '';
            $output[] = 'Congratulations! Your plugin passed all checks.';
            $output[] = '';
        }

        $output[] = '---';
        $output[] = '*Generated by [Retina](https://github.com/moonlightontheriver/retina) - PocketMine-MP Plugin Static Analyzer*';

        return implode("\n", $output);
    }

    private function formatIssue(Issue $issue, string $basePath): string
    {
        $severity = $issue->getSeverity();
        $icon = $severity->getIcon();

        $lines = [];
        $lines[] = sprintf(
            '- %s **%s** (Line %d): %s',
            $icon,
            $issue->getCategory()->getLabel(),
            $issue->getLine(),
            $issue->getMessage()
        );

        if ($issue->getSuggestion() !== null) {
            $lines[] = sprintf('  - 💡 *Suggestion:* %s', $issue->getSuggestion());
        }

        if ($issue->getSnippet() !== null) {
            $lines[] = '  ```php';
            foreach (explode("\n", $issue->getSnippet()) as $snippetLine) {
                $lines[] = '  ' . $snippetLine;
            }
            $lines[] = '  ```';
        }

        return implode("\n", $lines);
    }

    private function getRelativePath(string $path, string $basePath): string
    {
        if (str_starts_with($path, $basePath)) {
            return ltrim(substr($path, strlen($basePath)), '/\\');
        }
        return $path;
    }

    public function getExtension(): string
    {
        return 'md';
    }

    public function getMimeType(): string
    {
        return 'text/markdown';
    }
}
