<?php

declare(strict_types=1);

namespace Retina\Report\Format;

use Retina\Issue\Issue;
use Retina\Scanner\ScanResult;

class TextFormatter implements FormatterInterface
{
    public function format(ScanResult $result): string
    {
        $output = [];

        $output[] = str_repeat('=', 70);
        $output[] = '                     RETINA SCAN REPORT';
        $output[] = str_repeat('=', 70);
        $output[] = '';

        $output[] = 'PLUGIN INFORMATION';
        $output[] = str_repeat('-', 70);
        $output[] = sprintf('  Name:          %s', $result->getPluginName());
        $output[] = sprintf('  Version:       %s', $result->getPluginVersion());
        $output[] = sprintf('  Path:          %s', $result->getPluginPath());
        $output[] = sprintf('  Scan Date:     %s', $result->getScanDate()->format('Y-m-d H:i:s'));
        $output[] = sprintf('  Scan Duration: %.2f seconds', $result->getScanDuration());
        $output[] = '';

        $output[] = 'SUMMARY';
        $output[] = str_repeat('-', 70);
        $output[] = sprintf('  Files Scanned:     %d', $result->getScannedFileCount());
        $output[] = sprintf('  Files with Issues: %d', $result->getAffectedFileCount());
        $output[] = sprintf('  Total Issues:      %d', $result->getTotalIssueCount());
        $output[] = '';

        $summary = $result->getSummary();
        $nonZeroSummary = array_filter($summary, fn($count) => $count > 0);

        if (!empty($nonZeroSummary)) {
            $output[] = 'ISSUES BY CATEGORY';
            $output[] = str_repeat('-', 70);
            foreach ($nonZeroSummary as $category => $count) {
                $output[] = sprintf('  %-35s %d', $category . ':', $count);
            }
            $output[] = '';
        }

        $issuesByFile = $result->getIssuesByFile();

        if (!empty($issuesByFile)) {
            $output[] = 'DETAILED ISSUES';
            $output[] = str_repeat('=', 70);

            foreach ($issuesByFile as $file => $issues) {
                $relativeFile = $this->getRelativePath($file, $result->getPluginPath());
                $output[] = '';
                $output[] = sprintf('FILE: %s', $relativeFile);
                $output[] = str_repeat('-', 70);

                foreach ($issues as $index => $issue) {
                    $output[] = $this->formatIssue($issue, $index + 1);
                }
            }
        }

        if ($result->getTotalIssueCount() === 0) {
            $output[] = '';
            $output[] = str_repeat('=', 70);
            $output[] = '  [OK] No issues found! Your plugin passed all checks.';
            $output[] = str_repeat('=', 70);
        }

        $output[] = '';
        $output[] = str_repeat('-', 70);
        $output[] = 'Generated by Retina - PocketMine-MP Plugin Static Analyzer';
        $output[] = str_repeat('-', 70);

        return implode("\n", $output);
    }

    private function formatIssue(Issue $issue, int $index): string
    {
        $lines = [];

        $severityLabel = strtoupper($issue->getSeverity()->getLabel());
        $categoryLabel = $issue->getCategory()->getLabel();

        $lines[] = sprintf('  [%d] %s - %s', $index, $severityLabel, $categoryLabel);
        $lines[] = sprintf('      Line %d: %s', $issue->getLine(), $issue->getMessage());

        if ($issue->getSuggestion() !== null) {
            $lines[] = sprintf('      Suggestion: %s', $issue->getSuggestion());
        }

        if ($issue->getSnippet() !== null) {
            $lines[] = '      Code:';
            foreach (explode("\n", $issue->getSnippet()) as $snippetLine) {
                $lines[] = '        ' . $snippetLine;
            }
        }

        $lines[] = '';

        return implode("\n", $lines);
    }

    private function getRelativePath(string $path, string $basePath): string
    {
        if (str_starts_with($path, $basePath)) {
            return ltrim(substr($path, strlen($basePath)), '/\\');
        }
        return $path;
    }

    public function getExtension(): string
    {
        return 'txt';
    }

    public function getMimeType(): string
    {
        return 'text/plain';
    }
}
